jdbcSettings:
  url: "jdbc:mysql://localhost:3306/simpsons?useSSL=false&serverTimezone=UTC"
  username: "root"
  password: "root"
  driverClassName: "com.mysql.jdbc.Driver"
packageName: "edu.mum.cs544.hibernate2"